# Generated by Django 5.0 on 2023-12-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_vehicleatrentalstation_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='rent.rentalstation'),
        ),
    ]
